// Auto-generated by research pass: real, verified-via-search YouTube videos mapped to each
// lesson key in the (reduced) 24-lesson content plan across 6 courses. Every url is a distinct,
// real https://www.youtube.com/watch?v=<id> link found through web search (title/channel/
// existence confirmed via search result snippets), and genuinely covers that lesson's specific
// topic rather than just the broad course subject.

export const videoUrls: Record<
  string,
  { url: string; title: string; channel: string; confidence: 'high' | 'low'; note?: string }
> = {
  // ---------------------------------------------------------------------
  // Modern JavaScript Fundamentals
  // ---------------------------------------------------------------------
  'modern-javascript-fundamentals::1::variables-and-data-types': {
    url: 'https://www.youtube.com/watch?v=dzEieWaOJE0',
    title: 'JavaScript Let, Const & Var: A Complete Guide',
    channel: 'Web Dev Simplified',
    confidence: 'high',
  },
  'modern-javascript-fundamentals::1::operators-and-type-coercion': {
    url: 'https://www.youtube.com/watch?v=m4BfDo7KrQo',
    title: "Type Coercion Explained: Everyone's Favorite Subject",
    channel: 'Zero To Mastery',
    confidence: 'high',
  },
  'modern-javascript-fundamentals::2::function-declarations-and-expressions': {
    url: 'https://www.youtube.com/watch?v=ESA5ATgAlFw',
    title: 'JavaScript for Beginners #25 Function Declaration Versus Function Expressions',
    channel: 'dcode',
    confidence: 'high',
  },
  'modern-javascript-fundamentals::2::closures-and-scope': {
    url: 'https://www.youtube.com/watch?v=1S8SBDhA7HA',
    title: 'Javascript Closure Tutorial | Closures Explained',
    channel: 'Dave Gray',
    confidence: 'high',
  },

  // ---------------------------------------------------------------------
  // TypeScript Deep Dive
  // ---------------------------------------------------------------------
  'typescript-deep-dive::1::primitive-and-object-types': {
    url: 'https://www.youtube.com/watch?v=VBtenVZ13zI',
    title: 'TypeScript Types: Primitives, Objects, and Type Inference',
    channel: 'Codevolution',
    confidence: 'high',
  },
  'typescript-deep-dive::1::interfaces-vs-type-aliases': {
    url: 'https://www.youtube.com/watch?v=IXAT3If0pGI',
    title: 'TypeScript TYPES vs INTERFACES (Key Differences)',
    channel: 'Matt Pocock',
    confidence: 'high',
  },
  'typescript-deep-dive::2::generic-functions': {
    url: 'https://www.youtube.com/watch?v=I-KYdeqysME',
    title: 'TypeScript Generics Explained (Part 1): Generic Functions',
    channel: 'Codevolution',
    confidence: 'high',
  },
  'typescript-deep-dive::2::utility-types': {
    url: 'https://www.youtube.com/watch?v=ac2ocPGI97Q',
    title: 'Master TypeScript Utility Types: Partial, Pick, Omit, Record, Readonly, Required & More Explained',
    channel: 'Cosden Solutions',
    confidence: 'high',
  },

  // ---------------------------------------------------------------------
  // Machine Learning Foundations
  // ---------------------------------------------------------------------
  'machine-learning-foundations::1::what-machine-learning-is': {
    url: 'https://www.youtube.com/watch?v=m5998NezKAw',
    title: 'Machine Learning Tutorials - From Novice To Pro - #5 - Types of ML problems & how to distinguish',
    channel: 'Jeff Heaton',
    confidence: 'high',
  },
  'machine-learning-foundations::1::supervised-vs-unsupervised': {
    url: 'https://www.youtube.com/watch?v=ni8b8rBUx60',
    title: 'What is Machine Learning? Supervised (Regression vs Classification), Unsupervised (e.g. Clustering)',
    channel: 'Google Cloud Tech',
    confidence: 'high',
  },
  'machine-learning-foundations::2::linear-regression': {
    url: 'https://www.youtube.com/watch?v=vsWrXfO3wWw',
    title: 'Machine Learning Tutorial Python - 4: Gradient Descent and Cost Function',
    channel: 'codebasics',
    confidence: 'high',
  },
  'machine-learning-foundations::2::logistic-regression': {
    url: 'https://www.youtube.com/watch?v=slBI5YuVUTM',
    title: 'Logistic Regression - VISUALIZED!',
    channel: 'Majesty Coding',
    confidence: 'high',
  },

  // ---------------------------------------------------------------------
  // Python for Data Analysis with Pandas
  // ---------------------------------------------------------------------
  'python-for-data-analysis-with-pandas::1::series-and-dataframes': {
    url: 'https://www.youtube.com/watch?v=zmdjNSmRXF4',
    title: 'Python Pandas Tutorial (Part 2): DataFrame and Series Basics - Selecting Rows and Columns',
    channel: 'Corey Schafer',
    confidence: 'high',
  },
  'python-for-data-analysis-with-pandas::1::reading-and-writing-data': {
    url: 'https://www.youtube.com/watch?v=N6hyN6BW6ao',
    title: 'Python Pandas Tutorial (Part 11): Reading/Writing Data to Different Sources - Excel, JSON, SQL, Etc',
    channel: 'Corey Schafer',
    confidence: 'high',
  },
  'python-for-data-analysis-with-pandas::2::handling-missing-data': {
    url: 'https://www.youtube.com/watch?v=EaGbS7eWSs0',
    title: 'Python Pandas Tutorial 5: Handle Missing Data: fillna, dropna, interpolate',
    channel: 'codebasics',
    confidence: 'high',
  },
  'python-for-data-analysis-with-pandas::2::grouping-and-aggregation': {
    url: 'https://www.youtube.com/watch?v=Oo0Mio9Gx4A',
    title: 'Python Pandas Tutorial: GroupBy + Pivot Tables + Merge',
    channel: 'Keith Galli',
    confidence: 'high',
  },

  // ---------------------------------------------------------------------
  // Docker & Kubernetes Essentials
  // ---------------------------------------------------------------------
  'docker-and-kubernetes-essentials::1::images-and-containers': {
    url: 'https://www.youtube.com/watch?v=FCk5ylLjnxw',
    title: 'What is a Docker Container, Image and Layer?',
    channel: 'TechWorld with Nana',
    confidence: 'high',
  },
  'docker-and-kubernetes-essentials::1::writing-a-dockerfile': {
    url: 'https://www.youtube.com/watch?v=V0kTEk7YA70',
    title: 'Docker Multistage builds explained in 8 minutes',
    channel: 'Wolfulus',
    confidence: 'high',
  },
  'docker-and-kubernetes-essentials::2::pods-deployments-and-services': {
    url: 'https://www.youtube.com/watch?v=z9nYikBIqRA',
    title: 'Kubernetes Deployments and Services in 12 Minutes',
    channel: 'TechWorld with Nana',
    confidence: 'high',
  },
  'docker-and-kubernetes-essentials::2::configmaps-and-secrets': {
    url: 'https://www.youtube.com/watch?v=c8LBjmFPjM4',
    title: 'ConfigMaps and Secrets in Kubernetes',
    channel: 'Just me and Opensource',
    confidence: 'high',
  },

  // ---------------------------------------------------------------------
  // iOS App Development with Swift
  // ---------------------------------------------------------------------
  'ios-app-development-with-swift::1::variables-optionals-and-types': {
    url: 'https://www.youtube.com/watch?v=mK13jYq0VNc',
    title: 'Swift Tutorial: optionals, unwrapping, binding',
    channel: 'Sean Allen',
    confidence: 'high',
  },
  'ios-app-development-with-swift::1::functions-and-closures': {
    url: 'https://www.youtube.com/watch?v=Q7hc8LVGbew',
    title: "Swift Closures Explained - The ONLY video you'll ever need!",
    channel: 'Sean Allen',
    confidence: 'high',
  },
  'ios-app-development-with-swift::2::views-and-modifiers': {
    url: 'https://www.youtube.com/watch?v=Ty-yZyALIVc',
    title: 'View composition – Views and Modifiers SwiftUI Tutorial 8/10',
    channel: 'Hacking with Swift',
    confidence: 'high',
  },
  'ios-app-development-with-swift::2::state-and-data-binding': {
    url: 'https://www.youtube.com/watch?v=-ozfgfAILuc',
    title: 'SwiftUI @State, @Binding, @Observable, @Bindable & More Explained in 5 Minutes',
    channel: 'Vincent Pradeilles',
    confidence: 'high',
  },
}
